### ISSUE TITLE
device card disappears if device is offline

### ISSUE THREAD

**Issue by mason-xx** [ikaruswill/lovelace-fan-xiaomi#30] opened 2020-06-12 14:51 UTC
If the device is offline oder unplugged the card seems to disappear and with that the whole panel with all the elements where the card is configured. happens on latest version of hassio.
is it just me? for now i have it on a sparate panel since the fan has no battery status and you never know when it will dissappear.

**Comment by insajd** [comment] 2020-06-14 20:43
this is normal to happen with a reboot.
is this happening without a reboot? just turned off my fan from power, gonna check what's happening with fan off after 8h.

**Comment by ikaruswill** [comment] 2020-06-15 08:16
I haven't seen that happening with mine even on days when the fan was totally disconnected rom the WiFi due to router outage. That being said, I'm not on hassio, but on home-assistant docker `0.111.2`

**Comment by mason-xx** [comment] 2020-06-15 08:29
Okay I will see if I can reproduce it with more detail...

**Comment by ikaruswill** [comment] 2020-06-15 08:39
@mason-xx Thanks, appreciate it!

**Comment by insajd** [comment] 2020-06-15 10:06
I reproduced it, it was null pointer exception when reading regexped match here, when fan is offline
`speedLevel = speedRegexpMatch[1]`
Fixed with https://github.com/ikaruswill/lovelace-fan-xiaomi/pull/33

**Comment by mason-xx** [comment] 2020-06-15 14:24
nice, thanks a ton! will test when available :)

I also was able to reproduced it by disconnecting and switch of the fan. a little later the card/pane disappeard.

**Comment by insajd** [comment] 2020-06-16 08:08
Released a fix in 1.5.2 release

**Comment by mason-xx** [comment] 2020-06-16 08:13
thanks, looking good... card is back after update even the device is currently offline!

**Closed** 2020-06-16 08:51 UTC

**Comment by ikaruswill** [comment] 2020-06-16 10:41
@mason-xx Will release 1.5.2 officially with this fix and another :)
